HospitalSystem/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using HMS.Entities;
using HMS.Services;
using HospitalSystem.Areas.Dashboard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalSystem.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {


        AccomodationTypesService service = new AccomodationTypesService();
        // GET: Dashboard/AccomodationTypes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listing()
        {
            AccomodationTypesListingModel model = new AccomodationTypesListingModel();

            model.AccomodationType = service.GetAccomodationTypes();

            return PartialView("_Listing",model);
        }


        [HttpGet]
        public ActionResult ActionChng()
        {
            AccomodationTypesActionChngModel model = new AccomodationTypesActionChngModel();

            return PartialView("_ActionChng",model);
        }

        //[HttpPost]
        //public ActionResult ActionChng(AccomodationTypesActionChngModel acModel)
        //{
        //    AccomodationTypes accomType = new AccomodationTypes();
        //    accomType.Name = acModel.Name;

            

        //    return PartialView("_ActionChng", model);
        ////}
    }
}

HospitalSystem/Areas/Dashboard/Views/AccomodationTypes/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<h3>AccomodationTypes</h3>

<hr />

<div class="row mb-3">
    <div class="col col-md-12">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search here" >
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="button">Search</button>
                <button id="createBtn"  class="btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionChngModal">Create</button>
                <button class="btn btn-outline-danger" type="button">Reset</button>
            </div>
        </div>
    </div>
</div>







<div class="modal fade" id="actionChngModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        
    </div>
</div>

@{Html.RenderAction("Listing");}
<script type="text/javascript">
    $("#createBtn").click(function () {
        $.ajax({
           url: "@Url.Action("ActionChng", "AccomodationTypes")",
        })
        .done(function(response) {
            $("#actionChngModal .modal-dialog").html(response);
        });
    });
</script>

HospitalSystem/Areas/Dashboard/Views/AccomodationTypes/_ActionChng.cshtml
@model HospitalSystem.Areas.Dashboard.ViewModels.AccomodationTypesActionChngModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Create Accomodation Type</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" placeholder="Enter Accomodation Type" />
                </div>
                
               
                
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="actionbutton" type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div>
}
<script>
    $("#actionbutton").click(function () {
        $.ajax({
            url:@Url.Action("ActionChng","AccomodationTypes"),
            data:$("actionForm").serialize(), 
            type:"post"
        })
        .done(function(response){

        })
    })
</script>

HospitalSystem/Areas/Dashboard/Views/AccomodationTypes/_Listing.cshtml
@model HospitalSystem.Areas.Dashboard.ViewModels.AccomodationTypesListingModel

@if (Model != null && Model.AccomodationType != null && Model.AccomodationType.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">NAME</th>
                <th scope="col">ACTIONS</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var accomType in Model.AccomodationType)
            {
                <tr><td>@accomType.Name</td></tr>
                <tr>
                    <td>
                        <button type="button" class="btn btn-primary">Edit</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
            }

        </tbody>
    </table>


}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry, No record exists.
    </div>
}